apiVersion: v1beta
kind: Secret
metadata:
  name: fespa3_secret1
  namespace: fespa3
data:
  env_vars:
    - name: SECRET_ONE
      value: "This is the value of SECRET_ONE"
    - name: SECRET_TWO
      value: "This is the value of SECRET_TWO"
